### ISSUE TITLE
Py3 support

### ISSUE THREAD

**Issue by fabiog1901** [platform9/pf9-saml-auth#11]
Hello, it doesn't look like it's working on Python 3 yet.

```bash
fabio@dell: ~ $ python -V
Python 3.8.3
fabio@dell: ~ $ pip -V
pip 19.3.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
fabio@dell: ~ $ 
fabio@dell: ~ $ pip install https://github.com/platform9/oktaauth/archive/1.0.zip --user
Collecting https://github.com/platform9/oktaauth/archive/1.0.zip
  Using cached https://github.com/platform9/oktaauth/archive/1.0.zip
Requirement already satisfied (use --upgrade to upgrade): oktaauth==1.0 from https://github.com/platform9/oktaauth/archive/1.0.zip in ./.local/lib/python3.8/site-packages
Requirement already satisfied: argparse in ./.local/lib/python3.8/site-packages (from oktaauth==1.0) (1.4.0)
Requirement already satisfied: beautifulsoup4>=4.4 in /usr/lib/python3.8/site-packages (from oktaauth==1.0) (4.9.0)
Requirement already satisfied: requests>=2.8 in /usr/lib/python3.8/site-packages (from oktaauth==1.0) (2.22.0)
Requirement already satisfied: six in /usr/lib/python3.8/site-packages (from oktaauth==1.0) (1.14.0)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3.8/site-packages (from beautifulsoup4>=4.4->oktaauth==1.0) (1.9.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests>=2.8->oktaauth==1.0) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3.8/site-packages (from requests>=2.8->oktaauth==1.0) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests>=2.8->oktaauth==1.0) (1.25.7)
fabio@dell: ~ $ 
fabio@dell: ~ $ 
fabio@dell: ~ $ pip install pf9-saml-auth --user
ERROR: Could not find a version that satisfies the requirement pf9-saml-auth (from versions: none)
ERROR: No matching distribution found for pf9-saml-auth
fabio@dell: ~ $ 
```

**Comment by mattroark** [comment]
https://github.com/platform9/pf9-saml-auth/pull/9 purportedly added Python3 support and is merged currently. @shahpratikr Can you take a look?

**Comment by fabiog1901** [comment]
Extra info: 
```
fabio@dell: ~ $ cat /etc/redhat-release 
Fedora release 32 (Thirty Two)
fabio@dell: ~ $ uname -a
Linux dell 5.6.16-300.fc32.x86_64 #1 SMP Thu Jun 4 18:08:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

The same was seen on Centos8.

**Comment by shahpratikr** [comment]
@fabiog1901 can you please try installing pf9-saml-auth with https://github.com/platform9/pf9-saml-auth/archive/1.0.zip.
I have updated README as well.

**Comment by fabiog1901** [comment]
Thank you, it installs, but the plugins is still not recognized: **The plugin v3pf9samlokta could not be found**

```
fabio@dell: ~ $ python -m venv p9
fabio@dell: ~ $ source p9/bin/activate
(p9) fabio@dell: ~ $ 
(p9) fabio@dell: ~ $ 
(p9) fabio@dell: ~ $ pip -V
pip 19.3.1 from /home/fabio/p9/lib64/python3.8/site-packages/pip (python 3.8)
(p9) fabio@dell: ~ $ python -V
Python 3.8.3
(p9) fabio@dell: ~ $ pip install https://github.com/platform9/pf9-saml-auth/archive/1.0.zip
Collecting https://github.com/platform9/pf9-saml-auth/archive/1.0.zip
  Using cached https://github.com/platform9/pf9-saml-auth/archive/1.0.zip
[...]
Successfully installed PyYAML-5.3.1 argparse-1.4.0 beautifulsoup4-4.9.1 certifi-2020.4.5.2 chardet-3.0.4 debtcollector-2.1.0 idna-2.9 iso8601-0.1.12 keystoneauth1-4.0.0 lxml-4.5.1 msgpack-1.0.0 netaddr-0.7.19 netifaces-0.10.9 oktaauth-0.2 os-service-types-1.7.0 oslo.config-8.1.0 oslo.i18n-5.0.0 oslo.serialization-3.2.0 oslo.utils-4.2.1 pbr-5.4.5 pf9-saml-auth-1.0 pyparsing-2.4.7 python-keystoneclient-4.0.0 pytz-2020.1 requests-2.23.0 rfc3986-1.4.0 six-1.15.0 soupsieve-2.0.1 stevedore-2.0.0 urllib3-1.25.9 wrapt-1.12.1
(p9) fabio@dell: ~ $ 
(p9) fabio@dell: ~ $ pip install pf9-saml-auth
Requirement already satisfied: pf9-saml-auth in ./p9/lib/python3.8/site-packages (1.0)
[...]
(p9) fabio@dell: ~ $ 
(p9) fabio@dell: ~ $ pip install openstackclient
Collecting openstackclient
[...]
(p9) fabio@dell: ~ $ which openstack
~/p9/bin/openstack
(p9) fabio@dell: ~ $ 
(p9) fabio@dell: ~ $ 
(p9) fabio@dell: ~ $ env | grep OS_
OS_REGION_NAME=Fusion
OS_PROJECT_DOMAIN_ID=default
OS_AUTH_URL=https://xxxx.platform9.net/keystone/v3
OS_USER_DOMAIN_ID=default
OS_USERNAME=fabiog@xxxx
OS_IDENTITY_PROVIDER=IDP1
OS_AUTH_TYPE=v3pf9samlokta
OS_PROJECT_NAME=se
OS_PASSWORD=xxxxyyyzzz
OS_PROTOCOL=saml2
OS_IDENTITY_API_VERSION=3
(p9) fabio@dell: ~ $ 
(p9) fabio@dell: ~ $ openstack server show hello
The plugin v3pf9samlokta could not be found
```

**Comment by fabiog1901** [comment]
@shahpratikr were you able to replicate?

**Comment by shahpratikr** [comment]
@fabiog1901 I am seeing correct output for `openstack server show <name>` command. following are the settings which I used
(venv) ubuntu@pratik-dev-ubuntu:~$ which openstack
/home/ubuntu/venv/bin/openstack

(venv) ubuntu@pratik-dev-ubuntu:~$ env | grep OS_
OS_AUTH_URL=https://xxxxxxxx.platform9.horse/keystone/v3
OS_PROTOCOL=saml2
OS_REGION_NAME=RegionOne
OS_PROJECT_NAME=service
OS_PROJECT_DOMAIN_NAME=default
OS_IDENTITY_API_VERSION=3
OS_TENANT_NAME=service
OS_AUTH_TYPE=v3pf9samlokta
OS_IDENTITY_PROVIDER=IDP1
OS_INTERFACE=admin
OS_PASSWORD=xxxxxxxx
OS_USERNAME=xxxxxxxx

(venv) ubuntu@pratik-dev-ubuntu:~$ python -V
Python 3.6.9

(venv) ubuntu@pratik-dev-ubuntu:~$ pip -V
pip 20.1.1 from /home/ubuntu/venv/lib/python3.6/site-packages/pip (python 3.6)

(venv) ubuntu@pratik-dev-ubuntu:~$ openstack server show test-instance-2879 
+-----------------------------+---------------------------------------------------------------+
| Field                       | Value                                                         |
+-----------------------------+---------------------------------------------------------------+
| OS-DCF:diskConfig           | MANUAL                                                        |
| OS-EXT-AZ:availability_zone | nova                                                          |
| OS-EXT-STS:power_state      | Running                                                       |
| OS-EXT-STS:task_state       | None                                                          |
| OS-EXT-STS:vm_state         | active                                                        |
| OS-SRV-USG:launched_at      | 2020-07-01T08:11:25.000000                                    |
| OS-SRV-USG:terminated_at    | None                                                          |
| accessIPv4                  |                                                               |
| accessIPv6                  |                                                               |
| addresses                   | tb_provider_net=10.128.138.162                                |
| config_drive                |                                                               |
| created                     | 2020-07-01T08:10:39Z                                          |
| flavor                      | tiny.tiny 126 (aa54cda6-e175-46bf-9e00-5cb2d9cb615e)          |
| hostId                      | b478aed6cd069b180552c720146f854e880ba84c9c52681d0efe5c22      |
| id                          | 5ac34584-e229-402c-bf6c-a29ce532a270                          |
| image                       | ubuntu-12.04-cloudinit (a0d40467-1e58-0bd6-1708-c7c4894f8554) |
| key_name                    | None                                                          |
| name                        | test-instance-2879                                        |
| progress                    | 0                                                             |
| project_id                  | c7b56951330e4b97adc9a8650cb949ba                              |
| properties                  |                                                               |
| status                      | ACTIVE                                                        |
| updated                     | 2020-07-01T08:11:26Z                                          |
| user_id                     | 8c52f37b978e4649a8b727b7b27fe8d7                              |
| volumes_attached            |                                                               |
+-----------------------------+---------------------------------------------------------------+

**Comment by shahpratikr** [comment]
Closing the issue as there is no further update. Please reopen the issue if you see this problem again.
